import { AssessmentResult, BorrowerInput } from '../types/borrower'
import { inrCompact, pct } from './format'
import { LOAN_TYPE_OPTIONS } from './options'

export default function NegotiationCard({ answers, result }: { answers: BorrowerInput; result: AssessmentResult }) {
  const productLabel = LOAN_TYPE_OPTIONS.find((o) => o.value === result.rate.suggestedProduct)?.label ?? result.rate.suggestedProduct
  const bestOffer = answers.offersReceived?.[0]

  return (
    <div id="negotiation-card" className="bg-paper2 border border-ink p-6 md:p-8 space-y-6 print:border-black">
      <div className="flex items-baseline justify-between border-b border-ink pb-3">
        <div>
          <p className="text-xs tracking-wide font-semibold text-oxide">Negotiation Card</p>
          <p className="font-serif text-xl text-ink">Take this to the lender.</p>
        </div>
        <p className="font-mono text-xs text-inkmute">{new Date().toLocaleDateString('en-IN')}</p>
      </div>

      <div className="space-y-1">
        <p className="text-xs text-inkmute uppercase tracking-wide">Verdict</p>
        <p className="font-serif text-lg text-ink capitalize">{result.verdict.decision.replace('-', ' ')}</p>
      </div>

      <div className="grid grid-cols-2 gap-5">
        <div>
          <p className="text-xs text-inkmute uppercase tracking-wide">I can safely carry</p>
          <p className="font-serif text-2xl text-ink">{inrCompact(result.eligibility.safeCarry)}</p>
        </div>
        <div>
          <p className="text-xs text-inkmute uppercase tracking-wide">A lender may offer</p>
          <p className="font-serif text-2xl text-inkmute">{inrCompact(result.eligibility.lenderLikely)}</p>
        </div>
      </div>

      <div>
        <p className="text-xs text-inkmute uppercase tracking-wide">Fair rate for my profile</p>
        <p className="font-serif text-2xl text-ink">
          {pct(result.rate.low)} – {pct(result.rate.high)} <span className="text-base text-inkmute font-sans">on a {productLabel.toLowerCase()}</span>
        </p>
        <p className="text-sm text-inkmute">
          All-in APR (with fees): {pct(result.rate.aprLow)} – {pct(result.rate.aprHigh)}
        </p>
        {bestOffer && bestOffer.rate > 0 && (
          <p className="text-sm mt-1 font-medium text-oxide">
            {bestOffer.lender || 'Lender'} quoted {pct(bestOffer.rate)} — that is {bestOffer.rate > result.rate.high ? 'above' : 'within'} fair range.
          </p>
        )}
      </div>

      <div>
        <p className="text-xs text-inkmute uppercase tracking-wide">Monthly EMI I should agree to</p>
        <p className="font-serif text-2xl text-ink">{inrCompact(result.emi.ceiling)} / month</p>
        <p className="text-sm text-inkmute">If income drops or rates rise, this could reach {inrCompact(result.emi.stressCase.newEmi)}.</p>
      </div>

      {result.flags.length > 0 && (
        <div className="space-y-1 border-t border-line pt-4">
          <p className="text-xs text-inkmute uppercase tracking-wide">Worth mentioning</p>
          <ul className="text-sm text-ink space-y-1 list-disc pl-4">
            {result.flags.map((f, i) => (
              <li key={i}>{f}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="text-xs text-inkmute border-t border-line pt-4 leading-relaxed">
        {result.confidence.note} Generated by Borrower Copilot from self-reported answers — not a bureau
        report or a loan sanction. Use it to negotiate, not to replace the lender's own assessment.
      </p>
    </div>
  )
}
